version: '2'
services:
  nginx:
      build: ./nginx
      links:
          - api:api
          - swagger:swagger
          - jupyter:jupyter
      ports:
          - "80:80"
      volumes:
        - ./static:/var/www
  api:
      build: ./api
      links:
        - mongo:mongo
      depends_on:
        - mongo
      volumes:
        - ./api/data:/data
      environment:
        - DB_HOST=db
  mongo:
      image: mongo:latest
      volumes:
        - ./data/db:/data/db
  swagger:
      image: swaggerapi/swagger-ui
      volumes:
        - ./docs:/var/docs
      environment:
        - SWAGGER_JSON=/var/docs/swagger.json
  jupyter:
      image: jupyter/scipy-notebook
      volumes:
        - ./visual_search:/home/jovyan/work
      command: "start-notebook.sh --NotebookApp.password=sha1:d4598c04f6ae:a07462d1ad1d96a62b536b3ab8b9a628de850b1c"
      environment:
        - JUPYTER_LAB_ENABLE=yes
        - GRANT_SUDO=yes